#!/bin/bash
# cursor-cli Docker installer
# Builds the image and wires up a shell alias so you can use
# cursor-cli . from any project directory.
#
# Usage: bash docker-install.sh [--image <name>] [--tag <tag>] [--alias <name>]

set -euo pipefail

IMAGE_NAME="cursor-cli"
IMAGE_TAG="latest"
ALIAS_NAME="cursor-cli"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

info()    { echo -e "${CYAN}[info]${RESET} $*"; }
success() { echo -e "${GREEN}[ok]${RESET}  $*"; }
warn()    { echo -e "${YELLOW}[warn]${RESET} $*"; }
error()   { echo -e "${RED}[err]${RESET}  $*" >&2; }
die()     { error "$*"; exit 1; }

# ── Parse args ────────────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
  case "$1" in
    --image)  IMAGE_NAME="$2"; shift 2 ;;
    --tag)    IMAGE_TAG="$2";  shift 2 ;;
    --alias)  ALIAS_NAME="$2"; shift 2 ;;
    --help|-h)
      echo "Usage: bash docker-install.sh [--image <name>] [--tag <tag>] [--alias <name>]"
      exit 0 ;;
    *) die "Unknown option: $1" ;;
  esac
done

FULL_IMAGE="$IMAGE_NAME:$IMAGE_TAG"

# ── Preflight ─────────────────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}cursor-cli Docker installer${RESET}"
echo "────────────────────────────────────"
echo ""

command -v docker &>/dev/null || die "Docker is required. Install it from https://docs.docker.com/get-docker/"
docker info &>/dev/null       || die "Docker daemon is not running. Start Docker and retry."
success "Docker $(docker --version | awk '{print $3}' | tr -d ',') found"

# ── Build image ───────────────────────────────────────────────────────────────

info "Building image ${BOLD}$FULL_IMAGE${RESET}..."
docker build \
  --tag "$FULL_IMAGE" \
  --label "org.opencontainers.image.title=cursor-cli" \
  --label "org.opencontainers.image.description=Cursor Agent CLI" \
  --label "org.opencontainers.image.source=https://github.com/eroperez/cursor-cli" \
  "$REPO_DIR"

success "Image built: $FULL_IMAGE"

# ── Create persistent volume ──────────────────────────────────────────────────

VOLUME_NAME="cursor-cli-data"
if ! docker volume inspect "$VOLUME_NAME" &>/dev/null; then
  docker volume create "$VOLUME_NAME"
  success "Volume created: $VOLUME_NAME"
else
  success "Volume already exists: $VOLUME_NAME"
fi

# ── Write wrapper script ──────────────────────────────────────────────────────
# The wrapper passes the current directory into the container as /workspace
# and forwards all TTY / environment settings.

WRAPPER_SCRIPT="$(cat <<WRAPPER
#!/bin/bash
# cursor-cli Docker wrapper — generated by docker-install.sh

WORKSPACE="\${1:-.}"

# If first arg is a directory or ".", treat it as --cwd
if [[ -d "\$WORKSPACE" ]] || [[ "\$WORKSPACE" == "." ]]; then
  WORKSPACE="\$(cd "\$WORKSPACE" && pwd)"
  shift
  set -- --cwd /workspace "\$@"
fi

exec docker run --rm -it \\
  -e CURSOR_API_KEY="\${CURSOR_API_KEY:-}" \\
  -e CURSOR_MODEL="\${CURSOR_MODEL:-}" \\
  -v "\${WORKSPACE}:/workspace" \\
  -v "$VOLUME_NAME:/root/.cursor-cli" \\
  $FULL_IMAGE "\$@"
WRAPPER
)"

# Install wrapper to ~/.local/bin (preferred) or ~/bin as fallback
for INSTALL_DIR in "$HOME/.local/bin" "$HOME/bin"; do
  if [[ -d "$INSTALL_DIR" ]]; then
    break
  fi
done

if [[ ! -d "$INSTALL_DIR" ]]; then
  INSTALL_DIR="$HOME/.local/bin"
  mkdir -p "$INSTALL_DIR"
fi

WRAPPER_PATH="$INSTALL_DIR/$ALIAS_NAME"
echo "$WRAPPER_SCRIPT" > "$WRAPPER_PATH"
chmod +x "$WRAPPER_PATH"
success "Wrapper installed: $WRAPPER_PATH"

# ── PATH hint ─────────────────────────────────────────────────────────────────

if ! echo "$PATH" | grep -qF "$INSTALL_DIR"; then
  CURRENT_SHELL="$(basename "${SHELL:-bash}")"
  case "$CURRENT_SHELL" in
    zsh)  RC="$HOME/.zshrc" ;;
    bash) RC="$HOME/.bashrc" ;;
    fish) RC="$HOME/.config/fish/config.fish" ;;
    *)    RC="" ;;
  esac

  if [[ -n "$RC" ]] && ! grep -qF "$INSTALL_DIR" "$RC" 2>/dev/null; then
    echo "" >> "$RC"
    echo "# cursor-cli" >> "$RC"
    echo "export PATH=\"$INSTALL_DIR:\$PATH\"" >> "$RC"
  fi

  warn "$INSTALL_DIR not in PATH. Restart your shell or run:"
  echo -e "  ${CYAN}export PATH=\"$INSTALL_DIR:\$PATH\"${RESET}"
fi

# ── Done ─────────────────────────────────────────────────────────────────────

echo ""
echo -e "${GREEN}${BOLD}Docker installation complete!${RESET}"
echo ""
echo "  Set your API key (add to your shell profile to persist):"
echo -e "  ${CYAN}export CURSOR_API_KEY=\"crsr_...\"${RESET}"
echo ""
echo "  Launch in current directory:"
echo -e "  ${CYAN}$ALIAS_NAME .${RESET}"
echo ""
echo "  One-shot prompt:"
echo -e "  ${CYAN}$ALIAS_NAME . \"Explain the auth flow\"${RESET}"
echo ""
echo "  Specify a workspace explicitly:"
echo -e "  ${CYAN}$ALIAS_NAME /path/to/project \"Add tests\"${RESET}"
echo ""
echo -e "  Sessions and config are stored in Docker volume: ${BOLD}$VOLUME_NAME${RESET}"
